### PR TITLE
Replace software implementation of castagnoli crc32 with hardware implementation

### PR DESCRIPTION
**Pull request by rukai**
We found that castagnoli crc was a bottleneck in our application, this PR swaps our castagnoli crc implementation to [a hardware implementation](https://github.com/zowens/crc32c) which should improve performance significantly when the hardware is available.

I made [this PR](https://github.com/zowens/crc32c/pull/45) upstream to add a comparison between crc32c and crc crates but here are the results on my machine which has the required 4.2 SSE available:
image

crc32c vastly outperforms crc, it is getting throughputs of ~6GiB/s while crc is getting throughputs of ~500MiB/s

### CODE REVIEW

**Comment by tychedelia** [comment]
Hi @rukai sorry for being MIA, have been in the process of moving cross country. Will review this shortly!

**Comment by rukai** [comment]
No worries, hope your move goes well!

**Review by tychedelia — APPROVED** [review]
Looks great, thanks.

**Comment by tychedelia** [comment]
Just released https://crates.io/crates/kafka-protocol/0.7.0 including this.

**Comment by rukai** [comment]
Thanks!

**Pull request merged**
