### PR TITLE
CI fixes

### LINKED ISSUE #50: Run Clippy (and Rustfmt?) in CI
We missed a pretty useful suggestion, noticed in https://github.com/tychedelia/kafka-protocol-rs/pull/49. We should be running Clippy in our CI, and potentially rustfmt, although I know we've had questions before about whether the codegen files should be formatted since it can make reading them a bit more confusing.

### PR DESCRIPTION
**Pull request by tychedelia**
Closes #50 

Update our CI, fix warning, remove old unused xtask config.

### CODE REVIEW

**Comment by rukai** [comment]
Thanks for pushing this forward!

In order to avoid CI breaking when new rust versions are released I strongly recommend that we additionally:
* pin our rust version via rust-toolchain.toml e.g. https://github.com/shotover/shotover-proxy/blob/main/rust-toolchain.toml
  + this ensures that clippy lints do not start failing when a new rust version is released
  + It also ensures that the rust version used locally by developers is the same as each other and the same as CI which is quite convenient.
* check in our Cargo.lock files
  + this ensures that our dependencies do not fail to build due to relying on a rust version higher than the pinned rust version.
  + long ago the guidance was to never check in Cargo.lock for libraries, but that has since been adjusted - https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control

**Comment by tychedelia** [comment]
Thanks! These are great suggestions.

> * pin our rust version via rust-toolchain.toml

I wasn't quite sure whether we should include the extra targets, but did for good measure. The various compression libs we include do have some platform features, but I think they need to be toggled via rustc flags to be compiled by default. Maybe worth considering for the future.

**Review by rukai — APPROVED** [review]
looks good!

**Comment by rukai** [comment]
I dont have access to temporarily disable the required workflow, so you'll need to do that.

**Comment by tychedelia** [comment]
> I dont have access to temporarily disable the required workflow, so you'll need to do that.

Just replaced them with the correct checks in settings so you should be able to in the future 👍

**Pull request merged**
