### PR TITLE
Fix request header decoding/encoding

### PR DESCRIPTION
**Pull request by rukai**
Determining the correct version to use when encoding or decoding a request header requires a large match against all known messages and so should not be left to the user to implement.

Even [kafka-protocol-rs's own documentation](https://github.com/tychedelia/kafka-protocol-rs/blob/d8a289bbdebd71f89d52838810303902a7368773/src/lib.rs#L88) got this wrong, instructing the user to use the message version for decoding the header, which is incorrect.

The complexity is due to a poorly documented feature of kafka's protocol called "flexible versions".
This link talks about the general approach for figuring out the correct header version: https://stackoverflow.com/questions/71794315/questions-about-the-documentation-of-the-kafka-protocol
This link explains flexible versions: https://cwiki.apache.org/confluence/display/KAFKA/KIP-482%3A+The+Kafka+Protocol+should+Support+Optional+Tagged+Fields
The general idea is that the user does not get to choose which header versions to use, it is instead derived deterministically from the api_key and message version.

So to remove huge amounts of complexity from the user I have changed the RequestHeader to no longer implement Encodable/Decodable, instead it now directly implements its own encode/decode methods that do not take a version argument and instead derive the version from the contents of the header.

This is a breaking change, but a very necessary one IMO.

I have left ResponseHeader as is for now, but we may want to give it a similar treatment and have it take an ApiKey and message version from which the header version can be derived.
But any such change should go in a follow up PR and requires a bit of discussion because its not clear that it is actually an improvement.

### CODE REVIEW

**Comment by tychedelia** [comment]
Thanks, good catch on the docs, those were definitely wrong. I agree that this is a major source of confusion, but am wondering if there's a higher level way that we can handle this, i.e. by providing a nicer API for encoding both a header and message at the same time. For example, in one of my toy libraries, [I'm able to write this entirely generically](https://github.com/tychedelia/tower-kafka/blob/main/src/lib.rs#L47-L57), so while the `HeaderVersion` trait is a bit of a sharp edge, it only really needs to be implemented in one place. [Here](https://github.com/tychedelia/tower-kafka/blob/main/src/lib.rs#L96-L99) I'm defining aliases for the header+message pair, and I'm wondering if we might not want similar types in the library itself, so that we could implement the `HeaderVersion` logic on something that encodes the pair together. 

Regardless of approach, we definitely do want symmetry with the request/response types. It's obviously much more likely that someone is using this library to interact with an existing Kafka cluster rather than writing their own server, but [I'm at least one (in a very toy capacity)](https://github.com/tychedelia/josefine/blob/main/src/kafka/codec.rs#L77-L102) :).  But, as you can see from the link, matching over an enum is a pretty tedious pattern too, and I'm wondering if there's a better approach by unifying around some kind of generic header+message type.

Tagging @Diggsey to see if they have any input here.

**Comment by Diggsey** [comment]
It's been a while since I worked on my version and this crate obviously has a lot of changes since then that I'm unfamiliar with.

That said, this is how I handled versioning in my code:

https://github.com/Diggsey/franz/blob/master/src/network/broker.rs#L133

I don't think it was particularly complex: we intersect the version range supported by the server with the version range supported by the request type, and then pick the latest from that intersection to give use the "API version" to use for this request. `Req::header_version` then tells us which "header version" corresponds to that "API version" for this specific request type.

The server is required to return a response using the same "API version" as the request we sent, so then we use `Req::Response::header_version` to get the corresponding header version, and use that to decode the response header. Finally we decode the response itself using the "API version".

https://github.com/Diggsey/franz/blob/master/src/network/broker.rs#L72

IMO, it would be better to provide a separate higher level API (like the above) to handle encoding and decoding of messages and their corresponding headers correctly, rather than further complicate the message generator and encoding logic. It is important that the generator closely matches the logic in kafka itself.

**Comment by rukai** [comment]
> For example, in one of my libraries, [I'm able to write this entirely generically](https://github.com/tychedelia/tower-kafka/blob/main/src/lib.rs#L47-L57),

Thats a good point and I missed that approach for encoding RequestHeader.
However the story for decoding RequestHeader is still poor and that is important to my project.

Also, it looks like your kafka implementation is making the same mistake as the kafka-protocol-rs documentation is:
https://github.com/tychedelia/josefine/blob/557023615f2fdc2d2da5589284f139387d6ea00d/src/kafka/codec.rs#L44

I think that it makes sense for the header to not implement Encodable/Decodable because not only should the header determine its own version (needs a different method signature) but the header should also never be used in place of a message body (being generic across both headers and bodies is useless)
However it seems you both strongly value keeping the generator free of special cases so I will think and investigate what kind of a solution we could get with keeping header Encodable/Decodable and wrapping the header encode/decode.

A high level API that encodes/decodes both header and body at the same time would be nice.
But we also need to provide a usable low level API so that we can do things like parse the header and then only bother decoding the message body if we are interested in the specific api_key.

**Comment by tychedelia** [comment]
Thanks @rukai , I think this is helpful for me understanding your use case and I'm appreciating where you're coming from better (beyond the obvious sharp edges of the API that are clearly easy to get wrong 😅).

It makes sense to me that if you want to be able to incrementally deserialize the header only, using the `HeaderVersion` trait isn't going to work well. I'm definitely happy to accept API improvements here, but am inclined to agree that it should wrap the existing encode/decode logic. We don't have to over complicate it with solving all higher level concerns now, but I'd like to start differentiating between the low level bytes marshaling and providing some more lib-y features to help end users get it right (clearly agree that's an issue).

**Comment by rukai** [comment]
How do you feel about landing just the addition of `ApiKey::request_header_version` and `ApiKey::response_header_version`?
That would give me enough to go off in my project for now and then any higher level abstractions can be built on top of them.

Or would you rather come up with a holistic plan first?

**Comment by Diggsey** [comment]
> I think that it makes sense for the header to not implement Encodable/Decodable because not only should the header determine its own version (needs a different method signature)

I don't really agree that the header should determine its own version, or that it needs a different signature. In Kafka there is this idea that a struct can be encoded into some bytes using a specific encoding version. This is what is captured by the `Encodable` trait. Any expecations about what that version number should be is a higher level concern of the protocol itself, not of the underlying serialization code.

For the header to determine its own version it would need to also know about every message type that exists and what there associated header version should be. This is poor design as it introduces unnecessary coupling. It makes it harder to unit test the header encoding/decoding on its own. It means you can't easily adapt if upstream Kafka decides to use the RequestHeader type elsewhere in other places. The only concern of the RequestHeader type should be its fields and how to encode/decode/access them. This separation of concerns is especially important when the code is auto-generated like this.

**Comment by tychedelia** [comment]
> How do you feel about landing just the addition of `ApiKey::request_header_version` and `ApiKey::response_header_version`? That would give me enough to go off in my project for now and then any higher level abstractions can be built on top of them.

That sounds good to me for now.

**Pull request closed without merging**
